repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-yaml
        args: [--unsafe]
        exclude: "helm/"
      - id: end-of-file-fixer

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort # Sorts imports in py files

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black # Code formatting

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff # Code style and linting
        args: [ --fix ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-q", "-ll", "-s", "B104", "-r", "app"]
        additional_dependencies: ["pbr"]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets # So secrets aren't committed
